### ISSUE TITLE
Charms unavailable intermittently

### ISSUE THREAD

**Issue by canonical-cgregan** [juju/charmstore#780]
We've seen this across a few deploys and different charms, but always in the wee hours of the morning UTC

2017-11-01-04:16:51 ERROR 
2017-11-01-04:16:51 ERROR Deploying charm "cs:ceph-mon-12"
Deploying charm "cs:ceph-osd-246"
Deploying charm "cs:ceph-radosgw-251"
Deploying charm "cs:cinder-264"
Deploying charm "cs:cinder-ceph-227"
ERROR cannot deploy bundle: cannot add charm "cs:glance-259": cannot retrieve charm "cs:glance-259": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/glance-259/archive?channel=stable: dial tcp: lookup api.jujucharms.com on 10.245.208.26:53: read udp 10.245.214.12:50302->10.245.208.26:53: i/o timeout

Traceback (most recent call last):
  File "cdoqa-system-tests/cdoqa/deploy_prepared_bundle.py", line 91, in <module>
    sys.exit(deploy_prepared_bundle())
  File "cdoqa-system-tests/cdoqa/deploy_prepared_bundle.py", line 64, in deploy_prepared_bundle
    juju_client.deploy(deploy_args)
  File "/home/cdoqa/cdoqa-system-tests/cdoqa/juju.py", line 319, in deploy
    self._run(tuple(cmd))
  File "/home/cdoqa/cdoqa-system-tests/cdoqa/juju.py", line 84, in _run
    raise e
subprocess.CalledProcessError: Command '('juju', 'deploy', '/home/cdoqa/prepared_bundle.20171101041558/prepared_bundle.20171101041600.yaml')' returned non-zero exit status 1
Traceback (most recent call last):
  File "/var/lib/jenkins/cdoqa-system-tests/cdoqa/remote_run.py", line 37, in <module>
    remote_run()
  File "/var/lib/jenkins/cdoqa-system-tests/cdoqa/remote_run.py", line 32, in remote_run
    output = runner.run(args.command)
  File "/srv/mnt/jenkins/cdoqa-system-tests/cdoqa/utils.py", line 151, in run
    return subprocess.check_output(args, stdin=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ssh', '-o', 'UserKnownHostsFile /dev/null', '-o', 'StrictHostKeyChecking no', '-o', 'PasswordAuthentication no', 'cdoqa@10.62.42.253', '\ncdoqa-system-tests/setup/deploy_prepared_bundle.bash /home/cdoqa/testing_maas.yaml\n']' returned non-zero exit status 1
Build step 'Execute shell' marked build as failure

**Comment by cmars** [comment]
That looks like an issue that the host running the charmstore client is having with contacting the DNS server. Might try opening an RT to look into it.. or maybe just hard-code some public DNS servers into this client host if you don't need intranet DNS?

**Comment by cmars** [comment]
Feel free to reopen if you find more information on this that would indicate a charmstore server-side issue.
